name: Run Unit Test via Pytest  
  
on:
  push:
    branches: [master, main, dev/*, feature/*, release/*, staging/*, prod/*, qa]
  pull_request:
    branches: [master, main, dev/*, feature/*, release/*, staging/*, prod/*, qa]
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          # pytest and pytest-cov is optional if coverage already installed
          pip install pytest pylint pytest-cov 
          pip install -U coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  

      - name: Lint with pylint
        run: |
            pylint apps/home 
        continue-on-error: true   
      # - name: Lint with Ruff  
      #   run: |  
      #     pip install ruff  
      #     ruff -- --format=github --target-version=py310 .  
      #   continue-on-error: true  
      - name: Test with pytest  
        run: |  
          # pytest  -v -s  
          coverage run -m pytest  -v -s 

      - name: Generate Coverage Report  
        run: |  
            coverage report -m    
